/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppReceiptsRouteImport } from './routes/_app/receipts'
import { Route as AppPromotionsRouteImport } from './routes/_app/promotions'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppNgoRouteImport } from './routes/_app/ngo'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppGradebookRouteImport } from './routes/_app/gradebook'
import { Route as AppFeesRouteImport } from './routes/_app/fees'
import { Route as AppDebtorsRouteImport } from './routes/_app/debtors'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClassesRouteImport } from './routes/_app/classes'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppAcademicRouteImport } from './routes/_app/academic'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app/students.$studentId'
import { Route as AppNgoCentresRouteImport } from './routes/_app/ngo_.centres'
import { Route as AppNgoBeneficiariesIndexRouteImport } from './routes/_app/ngo_.beneficiaries.index'
import { Route as AppNgoBeneficiariesBeneficiaryIdRouteImport } from './routes/_app/ngo_.beneficiaries.$beneficiaryId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNgoRoute = AppNgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGradebookRoute = AppGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtorsRoute = AppDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicRoute = AppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppNgoCentresRoute = AppNgoCentresRouteImport.update({
  id: '/ngo_/centres',
  path: '/ngo/centres',
  getParentRoute: () => AppRoute,
} as any)
const AppNgoBeneficiariesIndexRoute =
  AppNgoBeneficiariesIndexRouteImport.update({
    id: '/ngo_/beneficiaries/',
    path: '/ngo/beneficiaries/',
    getParentRoute: () => AppRoute,
  } as any)
const AppNgoBeneficiariesBeneficiaryIdRoute =
  AppNgoBeneficiariesBeneficiaryIdRouteImport.update({
    id: '/ngo_/beneficiaries/$beneficiaryId',
    path: '/ngo/beneficiaries/$beneficiaryId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academic': typeof AppAcademicRoute
  '/accounting': typeof AppAccountingRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/debtors': typeof AppDebtorsRoute
  '/fees': typeof AppFeesRoute
  '/gradebook': typeof AppGradebookRoute
  '/inventory': typeof AppInventoryRoute
  '/ngo': typeof AppNgoRoute
  '/payments': typeof AppPaymentsRoute
  '/promotions': typeof AppPromotionsRoute
  '/receipts': typeof AppReceiptsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/users': typeof AppUsersRoute
  '/ngo/centres': typeof AppNgoCentresRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students/': typeof AppStudentsIndexRoute
  '/ngo/beneficiaries/$beneficiaryId': typeof AppNgoBeneficiariesBeneficiaryIdRoute
  '/ngo/beneficiaries/': typeof AppNgoBeneficiariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academic': typeof AppAcademicRoute
  '/accounting': typeof AppAccountingRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/debtors': typeof AppDebtorsRoute
  '/fees': typeof AppFeesRoute
  '/gradebook': typeof AppGradebookRoute
  '/inventory': typeof AppInventoryRoute
  '/ngo': typeof AppNgoRoute
  '/payments': typeof AppPaymentsRoute
  '/promotions': typeof AppPromotionsRoute
  '/receipts': typeof AppReceiptsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/users': typeof AppUsersRoute
  '/ngo/centres': typeof AppNgoCentresRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/students': typeof AppStudentsIndexRoute
  '/ngo/beneficiaries/$beneficiaryId': typeof AppNgoBeneficiariesBeneficiaryIdRoute
  '/ngo/beneficiaries': typeof AppNgoBeneficiariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/academic': typeof AppAcademicRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debtors': typeof AppDebtorsRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/gradebook': typeof AppGradebookRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/ngo': typeof AppNgoRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/receipts': typeof AppReceiptsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/ngo_/centres': typeof AppNgoCentresRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/ngo_/beneficiaries/$beneficiaryId': typeof AppNgoBeneficiariesBeneficiaryIdRoute
  '/_app/ngo_/beneficiaries/': typeof AppNgoBeneficiariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/academic'
    | '/accounting'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/debtors'
    | '/fees'
    | '/gradebook'
    | '/inventory'
    | '/ngo'
    | '/payments'
    | '/promotions'
    | '/receipts'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/users'
    | '/ngo/centres'
    | '/students/$studentId'
    | '/students/'
    | '/ngo/beneficiaries/$beneficiaryId'
    | '/ngo/beneficiaries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/academic'
    | '/accounting'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/debtors'
    | '/fees'
    | '/gradebook'
    | '/inventory'
    | '/ngo'
    | '/payments'
    | '/promotions'
    | '/receipts'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/staff'
    | '/users'
    | '/ngo/centres'
    | '/students/$studentId'
    | '/students'
    | '/ngo/beneficiaries/$beneficiaryId'
    | '/ngo/beneficiaries'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/academic'
    | '/_app/accounting'
    | '/_app/attendance'
    | '/_app/calendar'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/debtors'
    | '/_app/fees'
    | '/_app/gradebook'
    | '/_app/inventory'
    | '/_app/ngo'
    | '/_app/payments'
    | '/_app/promotions'
    | '/_app/receipts'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/users'
    | '/_app/ngo_/centres'
    | '/_app/students/$studentId'
    | '/_app/students/'
    | '/_app/ngo_/beneficiaries/$beneficiaryId'
    | '/_app/ngo_/beneficiaries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts': {
      id: '/_app/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ngo': {
      id: '/_app/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof AppNgoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gradebook': {
      id: '/_app/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof AppGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debtors': {
      id: '/_app/debtors'
      path: '/debtors'
      fullPath: '/debtors'
      preLoaderRoute: typeof AppDebtorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic': {
      id: '/_app/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AppAcademicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ngo_/centres': {
      id: '/_app/ngo_/centres'
      path: '/ngo/centres'
      fullPath: '/ngo/centres'
      preLoaderRoute: typeof AppNgoCentresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ngo_/beneficiaries/': {
      id: '/_app/ngo_/beneficiaries/'
      path: '/ngo/beneficiaries'
      fullPath: '/ngo/beneficiaries/'
      preLoaderRoute: typeof AppNgoBeneficiariesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ngo_/beneficiaries/$beneficiaryId': {
      id: '/_app/ngo_/beneficiaries/$beneficiaryId'
      path: '/ngo/beneficiaries/$beneficiaryId'
      fullPath: '/ngo/beneficiaries/$beneficiaryId'
      preLoaderRoute: typeof AppNgoBeneficiariesBeneficiaryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicRoute: typeof AppAcademicRoute
  AppAccountingRoute: typeof AppAccountingRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtorsRoute: typeof AppDebtorsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppGradebookRoute: typeof AppGradebookRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppNgoRoute: typeof AppNgoRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppUsersRoute: typeof AppUsersRoute
  AppNgoCentresRoute: typeof AppNgoCentresRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppNgoBeneficiariesBeneficiaryIdRoute: typeof AppNgoBeneficiariesBeneficiaryIdRoute
  AppNgoBeneficiariesIndexRoute: typeof AppNgoBeneficiariesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicRoute: AppAcademicRoute,
  AppAccountingRoute: AppAccountingRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtorsRoute: AppDebtorsRoute,
  AppFeesRoute: AppFeesRoute,
  AppGradebookRoute: AppGradebookRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppNgoRoute: AppNgoRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppUsersRoute: AppUsersRoute,
  AppNgoCentresRoute: AppNgoCentresRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppNgoBeneficiariesBeneficiaryIdRoute: AppNgoBeneficiariesBeneficiaryIdRoute,
  AppNgoBeneficiariesIndexRoute: AppNgoBeneficiariesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
